image: thinkr/rstudio4_0_2_geo_rs1.3.1056

variables:
  R_LIBS_USER: "ci/lib"

cache:
  key: global-cache
  paths:
      - ci/lib/

stages:
  - build
  - test
  - pkgdown
  - pkgdown-move
  - deploy

building:
  stage: build
  script:
    - mkdir -p $R_LIBS_USER
    # - apt update -qq && apt install -y libgdal-dev libproj-dev libgeos-dev libudunits2-dev libnode-dev libcairo2-dev libnetcdf-dev libharfbuzz-dev libfribidi-dev
    - apt update -qq && apt install -y libharfbuzz-dev libfribidi-dev
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));source("renv/activate.R")'
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));renv::restore(library = Sys.getenv("R_LIBS_USER"))'
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));install.packages(c("pkgdown", "DT", "devtools"))'
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));devtools::check()'

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

coverage:
    stage: test
    allow_failure: true
    when: on_success
    only:
        - master
        - dev
        - test-ci
    script:
        - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));covr::gitlab(quiet = FALSE);'
    artifacts:
        paths:
            - public
        expire_in: 30 days

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

integration:
    stage: pkgdown
    allow_failure: true
    when: on_success
    only:
        - master
        - dev
        - test-ci
    script:
        - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));remotes::install_github("ThinkR-open/thinkrtemplate")'
        - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));remotes::install_local();pkgdown::build_site()'
    artifacts:
        paths:
            - docs
        expire_in: 30 days

integration-test:
    stage: pkgdown-move
    dependencies:
        - integration
    only:
        - test-ci
    script:
        - mkdir -p public/test
        - wget https://git.thinkr.fr/ThinkR/Missions/azti.diades/-/jobs/artifacts/master/download?job=pages &&
          unzip -o download?job=pages &&
          rm download?job=pages &&
          echo "copied master artifacts" ||
          echo "copied master artifacts failed"
        - wget https://git.thinkr.fr/ThinkR/Missions/azti.diades/-/jobs/artifacts/dev/download?job=pages &&
          unzip -o download?job=pages &&
          rm download?job=pages &&
          echo "copied dev artifacts" ||
          echo "copied dev artifacts failed"
        - cp -r docs/* public/test
    artifacts:
        paths:
            - public
        expire_in: 30 days

integration-dev:
    stage: pkgdown-move
    dependencies:
        - integration
    only:
        - dev
    script:
        - mkdir -p public/dev
        - wget https://git.thinkr.fr/ThinkR/Missions/azti.diades/-/jobs/artifacts/master/download?job=pages &&
          unzip -o download?job=pages &&
          rm download?job=pages &&
          echo "copied master artifacts" ||
          echo "copied master artifacts failed"
        - cp -r docs/* public/dev
    artifacts:
        paths:
            - public
        expire_in: 30 days

integration-master:
    stage: pkgdown-move
    dependencies:
        - integration
    only:
        - master
    script:
        - mkdir -p public
        - wget https://git.thinkr.fr/ThinkR/Missions/azti.diades/-/jobs/artifacts/dev/download?job=pages &&
          unzip -o download?job=pages &&
          rm download?job=pages &&
          echo "copied dev artifacts" ||
          echo "copied dev artifacts failed"
        - cp -r docs/* public
    artifacts:
        paths:
            - public
        expire_in: 30 days

pages:
    stage: deploy
    script:
        - echo "deployment with cache ?"
    artifacts:
        paths:
            - public
    only:
        - master
        - dev
        - test-ci
        