default:
  golem_name: diades.atlas
  golem_version: 0.0.0.9000
  app_prod: no
  POSTGRES_DBNAME: diades
  POSTGRES_HOST: localhost
  POSTGRES_PORT: '5432'
  mongocollection: cache
  mongourl: mongodiades
  mongoport: '27017'
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
  mongourl: 127.0.0.1
  mongoport: '2811'
