on:
  push:
    branches:
      - main
      - master
      - dev
      - test-docker-ci
      - fix-pkgdown

name: pkgdown-docker-renv

jobs:
  pkgdown-docker-renv:
    runs-on: ubuntu-latest
    
    container: rocker/geospatial:4.0.1
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ubuntu-latest-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ubuntu-latest-renv-
      
      - name: Install system dependencies Linux
        run: sudo apt-get update -qq && apt install -y libharfbuzz-dev libfribidi-dev libgit2-dev
        
      - name: Install dependencies
        run: |
          source("renv/activate.R")
          renv::restore()
          renv::install("remotes")
          renv::install("pkgdown")
          remotes::install_local(upgrade = "never")
          remotes::install_github("ThinkR-open/thinkrtemplate", upgrade = "never")
        shell: Rscript {0}
        
      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'          