on:
  push:
    branches:
      - main
      - master
      - dev
      - test-docker-ci
  pull_request:
    branches:
      - main
      - master
      - dev


name: pkgdown-docker-renv

jobs:
  pkgdown-docker-renv:
    runs-on: ubuntu-latest
    
    container: rocker/geospatial:4.0.1
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Install system dependencies Linux
        run: sudo apt update -qq && apt install -y libharfbuzz-dev libfribidi-dev libgit2-dev

      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ubuntu-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ubuntu-renv-
          
      - name: Install dependencies
        run: |
          source("renv/activate.R")
          renv::restore()
          install.packages("pacman")
          pacman::p_load("remotes");install_local()
          pacman::p_load("remotes");install_github("ThinkR-open/thinkrtemplate")
          pacman::p_load("pkgdown");build_site()
        shell: Rscript {0}
        
      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          